
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const ADD_STAFF = 'ADD_STAFF';
export const DELETE_STAFF = 'DELETE_STAFF';
export const EDIT_STAFF = 'EDIT_STAFF';

export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
